from jianmu.self_learning.darwinforge.redqueen_metric_delta import review_metric_delta


def test_redqueen_metric_delta_detects_weak_category_boost(tmp_path):
    pre = {"categories": [{"category": "function", "success_rate": 0.9, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "review_weight": 1.0, "difficulty_level": 1, "coverage_gap": 0.0, "sample_count": 10}, {"category": "default_blocking", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "review_weight": 1.0, "difficulty_level": 1, "coverage_gap": 0.0, "sample_count": 10}, {"category": "unsupported_boundary", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "review_weight": 1.0, "difficulty_level": 1, "coverage_gap": 0.0, "sample_count": 10}]}
    post = {"categories": [{"category": "function", "success_rate": 0.9, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "category_event_count": 10, "actual_review_count": 12, "actual_difficulty_mean": 1, "actual_shape_diversity_count": 0, "actual_boundary_recheck_count": 0}, {"category": "default_blocking", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "category_event_count": 1, "actual_review_count": 1, "actual_difficulty_mean": 1, "actual_shape_diversity_count": 0, "actual_boundary_recheck_count": 1}, {"category": "unsupported_boundary", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "category_event_count": 1, "actual_review_count": 1, "actual_difficulty_mean": 1, "actual_shape_diversity_count": 0, "actual_boundary_recheck_count": 1}]}
    result = review_metric_delta(tmp_path, pre, post)
    assert result["weak_category_received_more_review"] is True


def test_redqueen_metric_delta_detects_stable_category_annealing(tmp_path):
    pre = {"categories": [{"category": "function", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "review_weight": 1.0, "difficulty_level": 1, "coverage_gap": 0.0, "sample_count": 10}, {"category": "default_blocking", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "review_weight": 1.0, "difficulty_level": 1, "coverage_gap": 0.0, "sample_count": 10}, {"category": "unsupported_boundary", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "review_weight": 1.0, "difficulty_level": 1, "coverage_gap": 0.0, "sample_count": 10}]}
    post = {"categories": [{"category": "function", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "category_event_count": 10, "actual_review_count": 10, "actual_difficulty_mean": 2, "actual_shape_diversity_count": 0, "actual_boundary_recheck_count": 0}, {"category": "default_blocking", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "category_event_count": 1, "actual_review_count": 1, "actual_difficulty_mean": 1, "actual_shape_diversity_count": 0, "actual_boundary_recheck_count": 1}, {"category": "unsupported_boundary", "success_rate": 1.0, "wrong_stdout_rate": 0.0, "timeout_rate": 0.0, "category_event_count": 1, "actual_review_count": 1, "actual_difficulty_mean": 1, "actual_shape_diversity_count": 0, "actual_boundary_recheck_count": 1}]}
    result = review_metric_delta(tmp_path, pre, post)
    assert result["stable_category_annealed"] is True
